# Source Prezto.
if [[ -s "$HOME/.zprezto/init.zsh" ]]; then
  source "$HOME/.zprezto/init.zsh"
fi

# Source dotfiles/aliases.
if [[ -s "$HOME/dotfiles/aliases.sh" ]]; then
  source "$HOME/dotfiles/aliases.sh"
fi

export PYTHONPATH="$HOME:$PYTHONPATH"

[ -f "$HOME"/.fzf.zsh ] && source "$HOME"/.fzf.zsh
source "$HOME"/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

