#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "$HOME/.zprezto/init.zsh" ]]; then
  source "$HOME/.zprezto/init.zsh"
fi

# Source dotfiles/aliases.
if [[ -s "$HOME/dotfiles/aliases.sh" ]]; then
  source "$HOME/dotfiles/aliases.sh"
fi

# Customize to your needs...
. ~/conda/etc/profile.d/conda.sh
conda activate py36

export PATH=$PATH:"~/.local/bin"
PYTHONPATH="/home/ronan:$PYTHONPATH"
PYTHONPATH="/home/ronan/milvor:$PYTHONPATH"
PYTHONPATH="/home/ronan/vision:$PYTHONPATH"
PYTHONPATH="/home/ronan/efficient_det:$PYTHONPATH"
export PYTHONPATH

export GOOGLE_APPLICATION_CREDENTIALS=~/.gconf/key.json
source /home/ronan/snap/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
export MILVUE_DATA_DIR='/home/ronan/data'
export TF_FORCE_GPU_ALLOW_GROWTH=true
export HTML_FOLDER="/home/ronan/scratch"
export HTML_ADRESS="http://grossac.milvue.com:6007"

